### ISSUE TITLE
COMBOBOX ISSUES

### ISSUE THREAD

**Issue by CXXXV** [LeaVerou/awesomplete#17212] opened 2020-02-26 16:16 UTC
1 - CB will not show in front of other div even with z-index: 999
2 - Drop down list lack scroll bar. Users want this. Standard with other drop downs.

**Comment by bbenjamin** [comment] 2020-04-10 18:58
HELLO ALL CAPS FAN :)
To increase the likelihood of issues being responded to, it's best to file unrelated items as separate issues. Item 1 is what you believe to be a bug, while item 2 is a feature request. The course of action would be different on those and they merit separate issues.

HOWEVER
I can address both points with this codepen:
https://codepen.io/bbbenjamin/pen/dyYPNoM

This codepen demonstrates that:
1- Combobox will appear in front of another div without any z-index change (perhaps this is specific to your site config?)
2- An example of a scrolling dropdown.

I believe the maintainer can close this because the Codepen demonstrates that (1) is not a bug, but something site specific, and (2) can already be achieved with a tiny amount of config.

**Comment by LeaVerou** [comment] 2020-04-11 04:45
Thank you @bbenjamin!
Furthermore, there is a combobox example RIGHT ON THE WEBSITE: https://leaverou.github.io/awesomplete/#advanced-examples

**Closed as completed by LeaVerou** 2020-04-11 04:45 UTC
