### ISSUE TITLE
Unable to disable sorting

### ISSUE THREAD

**Issue by jpodpro** [LeaVerou/awesomplete#17035] opened 2017-01-16 19:43 UTC
The unflexibility of this plugin leaves much to be desired. I have my data items ordered in a particular way and do not want them re-ordered when the dropdown is opened. However there appears to be no way to disable sorting.

**Comment by LeaVerou** [comment] 2017-01-23 17:28
Passing `function(){}` as the sort function doesn't work?

**Comment by davidkna** [comment] 2017-01-23 22:30
@LeaVerou depends if `Array.prototype.sort` is stable in the given browser. (also: duplicate of #16771)

**Comment by evenfrost** [comment] 2017-01-30 15:29
@LeaVerou Passing empty function does not work, only removing [this line](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L250) helps.

**Comment by vlazar** [comment] 2017-01-31 13:22
Closing since `sort: false` was introduced by #17043

**Closed as completed by vlazar** 2017-01-31 13:22 UTC
