### ISSUE TITLE
When entering a value that doesn't exist...

### ISSUE THREAD

**Issue by joacim-boive** [LeaVerou/awesomplete#9361] opened 2015-02-26 17:45 UTC
Flow:
Enter: "Javas"
Get: list of entries
Enter "2" ("Javas2")
Get: nothing
Enter: [backspace](leaving "Javas" again)
Get: nothing

Expected: list of entries

Tested in Safari Version 8.0.3 (10600.3.18) OS X 10.10.2

**Comment by LeaVerou** [comment] 2015-02-26 22:24
This is weird. I cannot reproduce it with my Safari 8.0.3. Pressing backspace and deleting the 2 just works and shows the list again. Can anyone else reproduce?

**Comment by ImBobby** [comment] 2015-02-27 03:11
I tried and facing same issue. Tested in Version 8.0.3 (10600.3.18) Yosemite. I also made a video just to make it clear. https://www.youtube.com/watch?v=kZAeB8RHJnE

**Comment by brushed** [comment] 2015-03-01 21:49
Apparently the "hidden" attribute doesn't get toggled when no values match the filter. 
I assume that also the ccs transition doesn't kick in properly when re-entering values that do match.

In the evaluate() function,  I replaced the 

``` javascript
    this.open();
```

by

``` javascript
    this[ this.ul.innerHTML == "" ? "close" : "open" ]();
```

which fixed the issue.

**Comment by LeaVerou** [comment] 2015-03-02 09:39
I would suggest `this.ul.children.length === 0` as a condition. Pull request please?

**Comment by vlazar** [comment] 2016-01-08 17:34
Fixed in merged #14804

**Closed as completed by vlazar** 2016-01-08 17:34 UTC
