### ISSUE TITLE
Multiple value example doesn't highlight 2nd and subsequent values

### ISSUE THREAD

**Issue by payne92** [LeaVerou/awesomplete#16884] opened 2016-04-19 12:40 UTC
The "multiple values" example on the main example/documentation page (here:  [https://leaverou.github.io/awesomplete/](https://leaverou.github.io/awesomplete/)) doesn't properly highlight 2nd and subsequent selected examples (in the drop down menu).

**Comment by vlazar** [comment] 2016-04-19 15:09
Closing as duplicate of #16814

**Closed as completed by vlazar** 2016-04-19 15:09 UTC
Labels: duplicate

**Comment by payne92** [comment] 2016-04-19 15:23
Sorry for duplicating an issue.

It's still an open problem, though, and all related problems have been marked as "closed".  

Is there an open issue tracking this problem?

Thanks!

**Comment by vlazar** [comment] 2016-04-19 16:03
Yes, it's #16814 and it's open :)
